#!/usr/bin/env bash

set -e

# Update system packages
sudo dnf update -y

# Setting up QEMU/KVM and all the tools required to manage VM
sudo dnf install -y qemu-kvm libvirt virt-install virt-manager virt-viewer \
                edk2-ovmf swtpm qemu-img guestfs-tools libosinfo tuned

# Download and install VirtIO repo
sudo wget https://fedorapeople.org/groups/virt/virtio-win/virtio-win.repo \
    -O /etc/yum.repos.d/virtio-win.repo

# Install virtio-win packages for Windows guests
sudo dnf install -y virtio-win

# Enable modular libvirt daemons
for drv in qemu interface network nodedev nwfilter secret storage; do
    sudo systemctl enable virt${drv}d.service
    sudo systemctl enable virt${drv}d{,-ro,-admin}.socket
done

# Reboot the system
sudo reboot